package validation;

import functionality.appController;
import user.Account;

public class ValidateAccount {
    private static final appController app = appController.getInstance();

    public static boolean validateAutoGenerated(String accountNumber) {
        if (accountNumber == null || accountNumber.isEmpty()) return false;
        return app.findAccount(accountNumber);
    }

}
