package user;

import validation.ValidateAccount;

import java.util.Objects;
import java.util.Random;

public class Account {

    private String name;
    private String accountNumber;

    private double balanceNow;
    private double balanceBefore;

    public Account(){
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getAccountNumber() {
        return accountNumber;
    }

    public void setAccountNumber() {
        this.accountNumber = generateAccountNumber();
    }

    public void setAccountNumber(String accountNumber) {
        this.accountNumber = accountNumber;
    }

    public double getBalanceBefore() {
        return balanceBefore;
    }

    public void setBalanceBefore(double balanceBefore) {
        this.balanceBefore = balanceBefore;
    }

    public double getBalanceNow() {
        return balanceNow;
    }

    public void setBalanceNow(double balanceNow) {
        this.balanceNow = balanceNow;
    }

    public String balanceToString() {
        if (balanceNow % 1 == 0) {
            return String.valueOf((int) balanceNow);
        } else {
            return String.valueOf(balanceNow);
        }
    }

    @Override
    public boolean equals(Object o) {
        if (!(o instanceof Account account)) return false;
        return Objects.equals(accountNumber, account.accountNumber);
    }

    @Override
    public String toString() {
        return "Account{" +
                "accountNumber='" + accountNumber + '\'' +
                ", name='" + name + '\'' +
                ", balanceNow=" + balanceNow +
                ", balanceBefore=" + balanceBefore +
                '}';
    }

    public static String generateAccountNumber() {
        Random rand = new Random();

        // 8-cifreni broj (00000000–99999999)
        int middle = rand.nextInt(100_000_000);

        // 2-cifreni broj (00–99)
        int last = rand.nextInt(100);

        String accountNumber = String.format("123-%08d-%02d", middle, last);

        if (!ValidateAccount.validateAutoGenerated(accountNumber)) {
            return generateAccountNumber();
        }

        return accountNumber;

    }


}
